sudo: false
language: python
python:
- '2.6'
- '2.7'
install:
- pip install requests
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v
deploy:
  provider: pypi
  distributions: sdist bdist bdist_wheel
  on:
    branch: master
  user: dt3310321
  password:
    secure: nOjTi1a/StH+NBZ0A8RFJ5VLwNR99ILxOK8khAVdLzm8tH+URD15Xo9ISkDmMPwBu+nWqI/EYckhzoOuGu0Lnl5Qri43FZ6R4eSsogYK3ozMjgv4lANu9lo9IlOWM7sEs9yYhTELz+t9K/v1rHFwZCWAT+X1CR6typ0Rl6I09O1o08OhG9LSjVRz6UCFoK63D95ZWOTVUfWdKdwKnLzweS5z05eF29aNDT61ftIt9GOpj5RX+k8ssbSL5MVTIE2Uh90y+VcPk1LjEoEZXlg37Q8rTO61QLQgXxvHapS6VbdehaoAlH8NLGxkw+bDx6I5NbK/ETrlN8UPH3iQ0MWEzbdYYStwrPaSAYXL18xPSy9B8ry6M3S2X+JD4VIS4dyTPAb88OgDo325HFJxsBn2ShRK9rkR+B4q8wykOpr8aaWwu+3H/VmWI2Y62JTYkzP+63GfYaK4aNPOuapBv2JHNKkV/IgAia7y9HzxCfyCi2w/WNj1PsnsCRmHrRdUh5yBQDlqfHk+vzvXBKJRIk8ixoMOTPgakPBIsfPFSSxaJk6CPr+T0O2fwsZNHQD+zSASRoWZBpMlCfyItsMeLnv8NzN/zAXFIU4vngCN2IHFZhSUmZy1yLaooKSpGeWGMUtXXg+RxRpKniXt91aE37hF/DZkTRnj3Q/JD07SSGAdgus=
