sudo: false
language: python
python:
- '2.6'
- '2.7'
install:
- pip install requests
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v
deploy:
  provider: pypi
  distributions: sdist bdist bdist_wheel
  user: dt3310321
  on:
    branch: master
  password:
    secure: Qlxj5v2PPn92RPuCeodRBY1FHgC0LyT0U9cuT5K6RZVzzRuMuuMrVLH3Abu9YSB62m/39gv60DpBYNLbKmVssglwIbxnceR0HeTiZNOemUjtUr35hhZ83gsZy3HARHfajaEUus3sw0S3Zb317dADtVSdJpN+O2fn7OSwP3tG8p2vc4xttkeuVsHXRSUUaUu+lmg+3k3FSpLsrRvFPTH9cxDPrChAqM+mdfyK5cfVYhEyCNq4lqrbEhmEPaURJW+lT6zcaBAT7hZuG2qTIfrOzPpXL1VMQGuq2t/hkD8+K5+hSu998YK0Y4hvBh8lLA1nXy4xTGpI9ESXnjKw+zm23/dEl/S9fRSFTCg+DfL3OZbCuVnlQx57kNuwckrVlZaMpaTi/d7/NZDL2arW1RfqrEY0F3MHfgRvbeU2bIV2zH0JlR+gQ8eD4b1Mda3Va+SSJY8IBJY2XAFo+hCTABUEZdH5hCiKI8rXZNtq243G95ZeBVIqzXqi9MdmlwZ6F+jnJs+8YjUv1ZMtHsvTD4bnBJ6h/Bom/fvwftVrIZnStULfzW8zYm0cK3BkGNOdFkGl/QJ4qtTnRfuCMdsoSOU7TjAm+5tNImo7bnap5C2t3l6LEf86SD8GFbUj/7TKIdAPWuAH+tKjTjHaMTDIjNbm6C9cOloISCxOx4fZ62bNrtA=
