sudo: false
language: python
python:
- '2.6'
- '2.7'
install:
- pip install requests
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v
deploy:
  provider: pypi
  distributions: sdist bdist bdist_wheel
  user: dt3310321
  password:
    secure: xzalzyubLEu5UA+TDoC5vNTAgvsn0Q98Dei/qyVG8ZjXDEE5wc45k6hZiRZ29EXKGcb8VSBh5QYjf8WjNJHHBoCcWCbbIv2NVcovX7wJ5oFaDukcKK/tdei0HkNDt0Q7JOhFbYLw4eolqkGqL89RBmTLV5XtrUvHIRd5Dj4Tk8OLhXZ2OaVxjTuwksLN870y599TR316cn8SPMrAHHJpjml9iaX4DJROT90RXP4vsKnbCVy2CStl+571IlgguL2BLaljXm4ipMLw7RYyRO2OpVmcqS8+0eMIbtDh9xGPMAQxQL2PI6++bfI4NJKdZg0eTHn7iIdKNMYAuj9pfC/U+m6kdbQ+rQAGIMooQuhMaVV5q8HW3SfD0UPwFYLpOv8u/pr383hM8B1zcdZ60V+STFgSm8yhDSPWtMUcQpxfKcM7Xbmh1oDdciNxY19rAHIGjWve8NtEp2ZX0mJfF6iFViCFZReK+HtEK0zkN1GYeoIeOwA4uL/JP2Qwq8tOB2xsnc/hJYfyINRyg7aYpcK+qLbhpcznd9AV3t6gSbY08tJO+A1TY5gE9yopU5xs7GXK20fgiKLVZIo9NZUL9yx//Wvm/5A2vvDnPuRWGpsbYfv0TKpR4l4KbPG/b8K/H9fr790mcajX6SCoVDW1uipZPCW1Nc93fvrSEqHGHmp0h8s=
  on:
    branch: master
