sudo: false
language: python
python:
- '2.6'
- '2.7'
install:
- pip install requests
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v
deploy:
  provider: pypi
  distributions: sdist bdist bdist_wheel
  user: dt3310321
  password:
    secure: v7heIpsR9c9vATCqumqYHRHBQODhqqYO5E4xtJDbxrqFr0zBnWuyozI2X2/2Bo4O1yRsM+EAVlGDzCmis4b7cM8Ufy91Cy4lt94DB6HKn8AAfc5Qhir4/jEb+M6JWEeRIFaMSki2oubVNr85dByTokpm7GwbNj/hB6yUkQSKvooCJWtNzeIe0FXvFGoOPzFDjUHBxQ7mkXPQhvloIsin1XeUn8ou5dvfXNerP7FVHpLj+o1dkkdYSVPAouWSd8ac4FbpmP/uT/ZyCR/xM/CydPl6JKsC8fRmCgFy3OJ5OT47g0g22Jdt+8uGqNLQUVduhDQNHrvlZyMJhdMJGKEEGhm0y6Z1IpJO1Au1XRNG+udQgyK3QPTdplA0+Wnw+ZXt+eLIOX3pAGkB4cE8sqnzWv5KoTLDTheeg9ZRIkVKQ+qGuy06VUbxZTQQ00QCH27ddyW6pgMQOt3Z5DLkq9J6XEnyXV+uWgkvbn5sjzlS7R/UCojBhhrzW2NZh0oB5w8jwSN+FFcDtOLU+b6Kl3TQ5yF5E2Vz07AFDV1sinr1EAFA0oG1K8WbXz7lzaHUJl49atXo/mJRFXGp7Veqp6w6tNczQJXkxm8Rzd+HJxqSi6rktc24ZXiHXMwc+8y3huJ4xIpxDUmbHNhDAhZvWs+kFIN/rx4W8iX0qUYfqxWcIq8=
  on:
    branch: master
